# Generated by Django 6.0.3
#
# Recovered from the production server, where it had been generated and applied
# but never committed. It is Django's default-auto-field drift: DonationCounter
# was created in 0012 with an explicit AutoField id, and DEFAULT_AUTO_FIELD is
# BigAutoField, so makemigrations proposes this every time it runs.
#
# Committed as-is, under the name production has already recorded as applied,
# so that every environment shares one linear migration history.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_cdonation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcounter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
