# Generated by Django 6.0.3 on 2026-09-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_cdonation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('snack_pack', 'Snack Packs'), ('smile_pack', 'Smile Packs'), ('diapers_child', 'Diapers - child'), ('adult_briefs', 'Adult briefs'), ('backpack_empty', 'Backpacks - empty'), ('backpack_filled', 'Backpacks - filled'), ('school_supplies', 'School supplies (assorted)'), ('turkey', 'Turkey'), ('chicken_turkey_breast', 'Chicken/Turkey Breast'), ('ham', 'Ham'), ('cart_small', 'Small cart (100 lbs)'), ('cart_large', 'Large cart (200 lbs)')], max_length=32)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='donations.donation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
